### PR TITLE
New apis

### PR DESCRIPTION
**Pull request by NathanPeake**
Moved internal apis into a new branch (should really be a new repo) using the new api loading system, created template api repo as well https://github.com/Bit-Studios/TemplateAPI started work on the wiki docs. pull also includes API doc generation

### CODE REVIEW

**Comment by NathanPeake** [comment]
Pausing pull for now as I have come across an issue and am in progress of fixing

**Comment by Rodentman87** [comment]
It might be worth it to move the dynamic api loading to another function and just call it during init, then there could be a way to clear the api handlers and reload everything while the game is running by just clearing the handlers and calling that same function.

**Comment by NathanPeake** [comment]
That can be a thing added in 0.2.0+

**Review by Rodentman87 — APPROVED** [review]
Looks good to me, I don't see any glaring issues

**Pull request merged**
